#
# Application
#
ag_shortener:
    resource: "@AGShortenerBundle/Resources/config/routing.yml"
    prefix:   /

ag_user:
    resource: "@AGUserBundle/Resources/config/routing.yml"
    prefix:   /

#
# Vendors
#
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#
# Core function (must be put at the end or will be matched everytime)
#
ag_shortener_redirect:
    path: /{token}
    defaults: { _controller: AGShortenerBundle:Public:clickRedirect }
    requirements:
        token: "[a-zA-Z0-9]+"
