ag_shortener_admin:
    path: /
    defaults: { _controller: AGShortenerBundle:Admin:index }

ag_shortener_admin_details:
    path: /liens/{id}/details
    defaults: { _controller: AGShortenerBundle:Link:details }
    requirements:
        id: \d+

ag_shortener_admin_remove:
    path: /liens/{id}/remove
    defaults: { _controller: AGShortenerBundle:Link:remove }
    requirements:
        id: \d+
