ag_shortener_admin:
    path: /
    defaults: { _controller: AGShortenerBundle:Admin:index }

ag_shortener_admin_details:
    path: /{id}/details
    defaults: { _controller: AGShortenerBundle:Admin:details }
    requirements:
        id: \d+

ag_shortener_admin_remove:
    path: /{id}/remove
    defaults: { _controller: AGShortenerBundle:Admin:remove }
    requirements:
        id: \d+
