ag_shortener_homepage:
    path:     /
    defaults: { _controller: AGShortenerBundle:Public:index }

ag_shortener_redirect:
    path: /s/{token}
    defaults: { _controller: AGShortenerBundle:Public:redirect }
    requirements:
        token: "[a-zA-Z0-9]+"
