ag_shortener_homepage:
    path:     /
    defaults: { _controller: AGShortenerBundle:Public:index }

ag_shortener_find:
    path: /retrouver-qrcode
    defaults: { _controller: AGShortenerBundle:Public:find }
