<?php

namespace AG\ShortenerBundle\Repository;
use AG\ShortenerBundle\Entity\Link;

/**
 * ClickRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClickRepository extends \Doctrine\ORM\EntityRepository
{
    public function getClicks(Link $link)
    {
        $qb = $this->createQueryBuilder('c')
            ->addSelect('COUNT(c.id) clickCount, YEAR(c.date) year, MONTH(c.date) month, DAY(c.date) day')
            ->where('c.link = :link')
            ->setParameter('link', $link)
            ->andWhere('c.date > :lastMonth')
            ->setParameter('lastMonth', new \DateTime('last month'))
            ->groupBy('year, month, day')
            ->orderBy('c.date', 'ASC')
        ;

        return $qb->getQuery()->getResult();
    }
}
