<?php

namespace AG\ShortenerBundle\Repository;
use AG\UserBundle\Entity\User;

/**
 * LinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllQuery(User $user)
    {
        return $this->createQueryBuilder('l')
            ->where('l.owner = :user')
            ->setParameter('user', $user)
            ->orderBy('l.createdAt', 'DESC')
            ->getQuery();
    }

    public function findAllAdminQuery()
    {
        return $this->createQueryBuilder('l')
            ->orderBy('l.createdAt', 'DESC')
            ->getQuery();
    }
}
