<?php

namespace AG\ShortenerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ScanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScanRepository extends EntityRepository
{
}
