<?php

namespace AG\ShortenerBundle\Repository;

use AG\ShortenerBundle\Entity\Link;
use Doctrine\ORM\EntityRepository;

/**
 * ScanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScanRepository extends EntityRepository
{
    public function getScans(Link $link)
    {
        $qb = $this->createQueryBuilder('s')
            ->addSelect('COUNT(s.id) scanCount, YEAR(s.date) year, MONTH(s.date) month, DAY(s.date) day')
            ->where('s.link = :link')
            ->setParameter('link', $link)
            ->groupBy('year, month, day')
            ->orderBy('s.date', 'ASC')
        ;

        return $qb->getQuery()->getResult();
    }
}
